from algoritmos import Classe
from analisa_dados import Analisa
        
if __name__ == "__main__":
    print("_____RELATÓRIO DE VELOCIDADE E EFICIÊNCIA_____")
    print(" ")
    print("Sera analisado o tempo medio vetores")
    print("com os valores de 0 a 999\n")
    print("Vetores com 10")
    # tempo medio de criação do vetor ordenado
    # print("vetor_ordenado: {:.8f}".format(Analisa.criaOrdenado(10)))
    # tempo medio de organização dos sorts
    print("  merge : {:.8f}".format(Analisa.calculaTempo(Classe.mergesort, 10)),"#tempo medio para o algoritmo organizar em segundos")
    print("  shell : {:.8f}".format(Analisa.calculaTempo(Classe.shellSort, 10)))
    print("  quick : {:.8f}".format(Analisa.calculaTempo(Classe.quickSort, 10)))
    print("  bubble: {:.8f}".format(Analisa.calculaTempo(Classe.bubbleSort, 10)))
    print("  select: {:.8f}".format(Analisa.calculaTempo(Classe.selectSort, 10)))
    print("  insert: {:.8f}".format(Analisa.calculaTempo(Classe.insertSort, 10)))
    print(" ")
    print("Vetores com 100")
    # print("vetor_ordenado {:.8f}".format(Analisa.criaOrdenado(100)))
    print("  merge : {:.8f}".format(Analisa.calculaTempo(Classe.mergesort, 100)))
    print("  shell : {:.8f}".format(Analisa.calculaTempo(Classe.shellSort, 100)))
    print("  quick : {:.8f}".format(Analisa.calculaTempo(Classe.quickSort, 100)))
    print("  bubble: {:.8f}".format(Analisa.calculaTempo(Classe.bubbleSort, 100)))
    print("  select: {:.8f}".format(Analisa.calculaTempo(Classe.selectSort, 100)))
    print("  insert: {:.8f}".format(Analisa.calculaTempo(Classe.insertSort, 100)))
    print(" ")
    print("Vetores com 1000")
    # print("vetor_ordenado {:.8f}".format(Analisa.criaOrdenado(1000)))
    print("  merge :  {:.8f}".format(Analisa.calculaTempo(Classe.mergesort, 1000)))
    print("  shell :  {:.8f}".format(Analisa.calculaTempo(Classe.shellSort, 1000)))
    print("  quick :  {:.8f}".format(Analisa.calculaTempo(Classe.quickSort, 1000)))
    print("  bubble:  {:.8f}".format(Analisa.calculaTempo(Classe.bubbleSort, 1000)))
    print("  select:  {:.8f}".format(Analisa.calculaTempo(Classe.selectSort, 1000)))
    print("  insert:  {:.8f}".format(Analisa.calculaTempo(Classe.insertSort, 1000)))
    # print(" ")
    # print("Vetores com 5000")
    # print("vetor_ordenado {:.8f}".format(Analisa.criaOrdenado(5000)))
    # print("  merge :  {:.8f}".format(Analisa.calculaTempo(Classe.mergesort, 5000)))
    # print("  shell :  {:.8f}".format(Analisa.calculaTempo(Classe.shellSort, 5000)))
    # print("  quick :  {:.8f}".format(Analisa.calculaTempo(Classe.quickSort, 5000)))
    # print("  bubble:  {:.8f}".format(Analisa.calculaTempo(Classe.bubbleSort, 5000)))
    # print("  select:  {:.8f}".format(Analisa.calculaTempo(Classe.selectSort, 5000)))
    # print("  insert:  {:.8f}".format(Analisa.calculaTempo(Classe.insertSort, 5000)))