from algoritmos import Classe
from analisa_dados import Analisa
        
if __name__ == "__main__":
    print("_____RELATÓRIO DE VELOCIDADE E EFICIÊNCIA_____")
    print(" ")
    print("Serão analisados:")
    print(" ")
    print("Vetores com 10 posições com valores de 0 a 999")
    print("média de tempo de criação de vetor ordenado  {:.16f} segundos".format(Analisa.criaOrdenado(10)))
    print("média de tempo de mergeSort  {:.16f} segundos".format(Analisa.calculaTempo(Classe.mergesort, 10)))
    print("média de tempo de shellSort  {:.16f} segundos".format(Analisa.calculaTempo(Classe.shellSort, 10)))
    print("média de tempo de quickSort  {:.16f} segundos".format(Analisa.calculaTempo(Classe.quickSort, 10)))
    print("média de tempo de bubbleSort {:.16f} segundos".format(Analisa.calculaTempo(Classe.bubbleSort, 10)))
    print("média de tempo de selectSort {:.16f} segundos".format(Analisa.calculaTempo(Classe.selectSort, 10)))
    print("média de tempo de insertSort {:.16f} segundos".format(Analisa.calculaTempo(Classe.insertSort, 10)))
    print(" ")
    print("Vetores com 100 posições com valores de 0 a 999")
    print("média de tempo de criação de vetor ordenado  {:.16f} segundos".format(Analisa.criaOrdenado(100)))
    print("média de tempo de mergeSort  {:.16f} segundos".format(Analisa.calculaTempo(Classe.mergesort, 100)))
    print("média de tempo de shellSort  {:.16f} segundos".format(Analisa.calculaTempo(Classe.shellSort, 100)))
    print("média de tempo de quickSort  {:.16f} segundos".format(Analisa.calculaTempo(Classe.quickSort, 100)))
    print("média de tempo de bubbleSort {:.16f} segundos".format(Analisa.calculaTempo(Classe.bubbleSort, 100)))
    print("média de tempo de selectSort {:.16f} segundos".format(Analisa.calculaTempo(Classe.selectSort, 100)))
    print("média de tempo de insertSort {:.16f} segundos".format(Analisa.calculaTempo(Classe.insertSort, 100)))
    print(" ")
    print("Vetores com 1000 posições com valores de 0 a 999")
    print("média de tempo de criação de vetor ordenado  {:.16f} segundos".format(Analisa.criaOrdenado(1000)))
    print("média de tempo de mergeSort  {:.16f} segundos".format(Analisa.calculaTempo(Classe.mergesort, 1000)))
    print("média de tempo de shellSort  {:.16f} segundos".format(Analisa.calculaTempo(Classe.shellSort, 1000)))
    print("média de tempo de quickSort  {:.16f} segundos".format(Analisa.calculaTempo(Classe.quickSort, 1000)))
    print("média de tempo de bubbleSort {:.16f} segundos".format(Analisa.calculaTempo(Classe.bubbleSort, 1000)))
    print("média de tempo de selectSort {:.16f} segundos".format(Analisa.calculaTempo(Classe.selectSort, 1000)))
    print("média de tempo de insertSort {:.16f} segundos".format(Analisa.calculaTempo(Classe.insertSort, 1000)))